[theme]
primaryColor = "#D94B64"
backgroundColor = "#F5F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#152238"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true

